type: web
name: pattern-api
runtime: python
buildCommand: "pip install -r requirements.txt"
startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
envVars:
  - key: FTP_HOST
    fromDotEnv: true
  - key: FTP_USER
    fromDotEnv: true
  - key: FTP_PASS
    fromDotEnv: true
  - key: FTP_PORT
    fromDotEnv: true
  - key: REMOTE_PATH
    fromDotEnv: true
